[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[[build.args]]
name = "VITE_STRIPE_PK"
value = "${VITE_STRIPE_PK}"

[[build.args]]
name = "VITE_INSFORGE_BASE_URL"
value = "${VITE_INSFORGE_BASE_URL}"

[[build.args]]
name = "VITE_INSFORGE_ANON_KEY"
value = "${VITE_INSFORGE_ANON_KEY}"

[deploy]
startCommand = "node server.cjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
