// Auto-generated by scripts/build-partials.js — DO NOT EDIT DIRECTLY
// Run `node scripts/build-partials.js` to regenerate.
//
// CTA Slot Contract:
//   cta prop accepts CtaAction[] with { label, href, variant?, icon? }
//   Empty array hides CTAs. Omitted prop uses variant default.

import { useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';

// ─── Types ────────────────────────────────────────────────────

export type CtaVariant = 'primary' | 'secondary' | 'icon';

export interface CtaAction {
  label: string;
  href?: string;
  onClick?: () => void;
  variant?: CtaVariant;
  icon?: ReactNode;
}

export type HeaderVariant = 'landing' | 'marketing' | 'legal' | 'app';

export interface HeaderProps {
  /** Determines default nav items and default CTA */
  variant: HeaderVariant;
  /** Override default CTAs. Pass [] to hide. */
  cta?: CtaAction[];
  /** Override default nav items */
  navItems?: Array<{ label: string; href: string }>;
  /** Suppress the entire CTA area (shortcut for cta=[]) */
  hideCta?: boolean;
  /** Extra elements after nav (e.g. theme toggle) */
  extra?: ReactNode;
  className?: string;
}

// ─── Icon components (inline SVGs) ──────────────────────────

function BellIcon({ className }: { className?: string }) {
  return (
    <svg className={className ?? 'w-5 h-5'} viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="M10 2a6 6 0 00-6 6v3l-1 3h14l-1-3V8a6 6 0 00-6-6z"/>
      <path d="M7.5 14a2.5 2.5 0 005 0"/>
    </svg>
  );
}

function EcoLogo() {
  return (
    <svg className="w-7 h-7" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg" aria-label="Eco-Auditor logo">
      <rect width="28" height="28" rx="7" fill="currentColor" className="text-brand-600"/>
      <path d="M8 20V8l6 4 6-4v12" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

function MenuIcon() {
  return <svg className="w-5 h-5" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"><path d="M3 5.5h14M3 10h14M3 14.5h14" /></svg>;
}

// ─── Variant defaults ───────────────────────────────────────

const DEFAULT_NAV: Record<HeaderVariant, Array<{ label: string; href: string }>> = {
  landing: [
    { label: 'Features', href: '#features' },
    { label: 'How It Works', href: '#how-it-works' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'Methodology', href: '/methodology' },
    { label: 'Security', href: '/security' },
  ],
  marketing: [
    { label: 'Features', href: '/#features' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'Methodology', href: '/methodology' },
    { label: 'Sample Report', href: '/sample-report' },
    { label: 'Security', href: '/security' },
  ],
  // P1-05: legal/contact pages keep the same global navigation as marketing
  // pages so a prospect reaching a policy or contact page retains a route
  // back to product evaluation.
  legal: [
    { label: 'Pricing', href: '/pricing' },
    { label: 'Methodology', href: '/methodology' },
    { label: 'Sample Report', href: '/sample-report' },
    { label: 'Security', href: '/security' },
  ],
  app: [
  ],
};

const DEFAULT_CTA: Record<HeaderVariant, CtaAction[]> = {
  landing: [
    { label: 'Log In', href: '/login', variant: 'secondary' },
    { label: 'Start Free Trial', href: '/signup', variant: 'primary' },
  ],
  marketing: [
    { label: 'Start Free Trial', href: '/signup', variant: 'primary' },
    { label: 'Book a Demo', href: '/demo', variant: 'secondary' },
  ],
  // P1-04: canonical CTA taxonomy — one label maps to one intent.
  legal: [
    { label: 'Log In', href: '/login', variant: 'secondary' },
    { label: 'Start Free Trial', href: '/signup', variant: 'primary' },
  ],
  app: [
    { label: 'Notifications', icon: <BellIcon />, variant: 'icon' },
  ],
};

const STICKY: Record<HeaderVariant, boolean> = {
  landing: true,
  marketing: true,
  legal: false,
  app: false,
};

// ─── Component ───────────────────────────────────────────────

export default function Header({ variant, cta, navItems, hideCta, extra, className }: HeaderProps) {
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const resolvedNav = navItems ?? DEFAULT_NAV[variant];
  const resolvedCta = hideCta ? [] : (cta ?? DEFAULT_CTA[variant]);
  const isSticky = STICKY[variant];
  const showMobileMenuButton = resolvedNav.length > 0 || resolvedCta.some((action) => action.href);

  return (
    <>
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-[100] focus:px-4 focus:py-2 focus:bg-brand-600 focus:text-white focus:rounded-lg focus:text-sm focus:font-semibold"
      >
        Skip to main content
      </a>
    <header
      className={`${isSticky ? 'sticky top-0 ' : ''}z-50 border-b border-surface-200/80 dark:border-surface-800/80 bg-white/90 dark:bg-surface-900/90 backdrop-blur-md${className ? ' ' + className : ''}`}>
      <div className="max-w-7xl mx-auto px-6 py-3 flex items-center justify-between">
        {/* Logo */}
        <Link to="/" className="flex items-center gap-2.5">
          <EcoLogo />
          <span className="font-semibold text-sm text-surface-900 dark:text-white tracking-tight">Eco-Auditor</span>
        </Link>

        {/* Nav items */}
        {resolvedNav.length > 0 && (
          <nav className="hidden md:flex items-center gap-6 text-sm" aria-label="Main navigation">
            {resolvedNav.map((item) => (
              item.href.startsWith('#') ? (
                <a key={item.href} href={item.href} className="inline-flex items-center no-underline text-surface-600 dark:text-surface-400 hover:text-surface-900 dark:hover:text-white transition-colors">{item.label}</a>
              ) : (
                <Link key={item.href} to={item.href} className="inline-flex items-center no-underline text-surface-600 dark:text-surface-400 hover:text-surface-900 dark:hover:text-white transition-colors">{item.label}</Link>
              )
            ))}
          </nav>
        )}

        {/* CTA slot + extras */}
        <div className="flex items-center gap-3">
          {showMobileMenuButton && (
            <button
              type="button"
              onClick={() => setMobileNavOpen((open) => !open)}
              className="md:hidden p-1.5 rounded-lg hover:bg-surface-100 dark:hover:bg-surface-800 text-surface-500 transition-colors"
              aria-label="Toggle navigation menu"
              aria-expanded={mobileNavOpen}
            >
              <MenuIcon />
            </button>
          )}
          {extra}
          {resolvedCta.map((action, i) => {
            const key = action.href ?? action.label;
            if (action.variant === 'icon') {
              return (
                <button key={key} type="button" onClick={action.onClick} className="relative p-1.5 rounded-lg hover:bg-surface-100 dark:hover:bg-surface-800 text-surface-500 transition-colors" aria-label={action.label}>
                  {action.icon}
                </button>
              );
            }
            if (action.variant === 'secondary' || (resolvedCta.length > 1 && i < resolvedCta.length - 1)) {
              return (
                <Link key={key} to={action.href ?? '#'} onClick={action.onClick} className="hidden sm:inline-flex btn-secondary text-sm !py-2 !px-5">{action.label}</Link>
              );
            }
            return (
              <Link key={key} to={action.href ?? '#'} onClick={action.onClick} className="hidden sm:inline-flex btn-primary text-sm !py-2 !px-5">{action.label}</Link>
            );
          })}
        </div>
      </div>
      {mobileNavOpen && showMobileMenuButton && (
        <div className="md:hidden border-t border-surface-200/80 dark:border-surface-800/80 bg-white dark:bg-surface-900">
          {resolvedNav.length > 0 && (
            <nav className="px-6 py-4 space-y-1" aria-label="Mobile navigation">
              {resolvedNav.map((item) => (
                item.href.startsWith('#') ? (
                  <a key={item.href} href={item.href} onClick={() => setMobileNavOpen(false)} className="block rounded-lg px-3 py-2 text-sm font-medium no-underline text-surface-700 dark:text-surface-300 hover:bg-surface-100 dark:hover:bg-surface-800 transition-colors">{item.label}</a>
                ) : (
                  <Link key={item.href} to={item.href} onClick={() => setMobileNavOpen(false)} className="block rounded-lg px-3 py-2 text-sm font-medium no-underline text-surface-700 dark:text-surface-300 hover:bg-surface-100 dark:hover:bg-surface-800 transition-colors">{item.label}</Link>
                )
              ))}
            </nav>
          )}
          {resolvedCta.some((action) => action.href) && (
            <div className="px-6 pb-4 flex flex-col gap-2">
              {resolvedCta.filter((action) => action.href).map((action) => (
                <Link
                  key={action.href ?? action.label}
                  to={action.href ?? '#'} 
                  onClick={() => { action.onClick?.(); setMobileNavOpen(false); }}
                  className={action.variant === 'secondary' ? 'btn-secondary justify-center text-sm !py-2 !px-5' : 'btn-primary justify-center text-sm !py-2 !px-5'}
                >
                  {action.label}
                </Link>
              ))}
            </div>
          )}
        </div>
      )}
    </header>
    </>
  );
}
