// Auto-generated by scripts/build-partials.js — DO NOT EDIT DIRECTLY
// Run `node scripts/build-partials.js` to regenerate.
//
// CTA Slot Contract:
//   cta prop accepts CtaAction[] with { label, href, variant?, icon? }
//   Empty array hides CTAs. Omitted prop uses variant default.

import { Link } from 'react-router-dom';
import type { ReactNode } from 'react';

// ─── Types ────────────────────────────────────────────────────

export type CtaVariant = 'primary' | 'secondary' | 'icon';

export interface CtaAction {
  label: string;
  href?: string;
  onClick?: () => void;
  variant?: CtaVariant;
  icon?: ReactNode;
}

export type HeaderVariant = 'landing' | 'marketing' | 'legal' | 'app';

export interface HeaderProps {
  /** Determines default nav items and default CTA */
  variant: HeaderVariant;
  /** Override default CTAs. Pass [] to hide. */
  cta?: CtaAction[];
  /** Override default nav items */
  navItems?: Array<{ label: string; href: string }>;
  /** Suppress the entire CTA area (shortcut for cta=[]) */
  hideCta?: boolean;
  /** Extra elements after nav (e.g. theme toggle) */
  extra?: ReactNode;
  className?: string;
}

// ─── Icon components (inline SVGs) ──────────────────────────

function BellIcon({ className }: { className?: string }) {
  return (
    <svg className={className ?? 'w-5 h-5'} viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="M10 2a6 6 0 00-6 6v3l-1 3h14l-1-3V8a6 6 0 00-6-6z"/>
      <path d="M7.5 14a2.5 2.5 0 005 0"/>
    </svg>
  );
}

function EcoLogo() {
  return (
    <svg className="w-7 h-7" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg" aria-label="Eco-Auditor logo">
      <rect width="28" height="28" rx="7" fill="currentColor" className="text-brand-600"/>
      <path d="M8 20V8l6 4 6-4v12" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}

// ─── Variant defaults ───────────────────────────────────────

const DEFAULT_NAV: Record<HeaderVariant, Array<{ label: string; href: string }>> = {
  landing: [
    { label: 'Features', href: '#features' },
    { label: 'How It Works', href: '#how-it-works' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'Methodology', href: '/methodology' },
    { label: 'Security', href: '/security' },
  ],
  marketing: [
    { label: 'Features', href: '/#features' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'Methodology', href: '/methodology' },
    { label: 'Sample Report', href: '/sample-report' },
    { label: 'Security', href: '/security' },
  ],
  legal: [
  ],
  app: [
  ],
};

const DEFAULT_CTA: Record<HeaderVariant, CtaAction[]> = {
  landing: [
    { label: 'Log In', href: '/login', variant: 'secondary' },
    { label: 'Start Free Trial', href: '/signup', variant: 'primary' },
  ],
  marketing: [
    { label: 'Start Free Trial', href: '/signup', variant: 'primary' },
    { label: 'Book a Demo', href: '/contact', variant: 'secondary' },
  ],
  legal: [
  ],
  app: [
    { label: 'Notifications', icon: <BellIcon />, variant: 'icon' },
  ],
};

const STICKY: Record<HeaderVariant, boolean> = {
  landing: true,
  marketing: true,
  legal: false,
  app: false,
};

// ─── Component ───────────────────────────────────────────────

export default function Header({ variant, cta, navItems, hideCta, extra, className }: HeaderProps) {
  const resolvedNav = navItems ?? DEFAULT_NAV[variant];
  const resolvedCta = hideCta ? [] : (cta ?? DEFAULT_CTA[variant]);
  const isSticky = STICKY[variant];

  return (
    <header
      className={`${isSticky ? 'sticky top-0 ' : ''}z-50 border-b border-surface-200/80 dark:border-surface-800/80 bg-white/90 dark:bg-surface-900/90 backdrop-blur-md${className ? ' ' + className : ''}`}>
      <div className="max-w-7xl mx-auto px-6 py-3 flex items-center justify-between">
        {/* Logo */}
        <Link to="/" className="flex items-center gap-2.5">
          <EcoLogo />
          <span className="font-semibold text-sm text-surface-900 dark:text-white tracking-tight">Eco-Auditor</span>
        </Link>

        {/* Nav items */}
        {resolvedNav.length > 0 && (
          <nav className="hidden md:flex items-center gap-6 text-sm" aria-label="Main navigation">
            {resolvedNav.map((item) => (
              item.href.startsWith('#') ? (
                <a key={item.href} href={item.href} className="inline-flex items-center no-underline text-surface-600 dark:text-surface-400 hover:text-surface-900 dark:hover:text-white transition-colors">{item.label}</a>
              ) : (
                <Link key={item.href} to={item.href} className="inline-flex items-center no-underline text-surface-600 dark:text-surface-400 hover:text-surface-900 dark:hover:text-white transition-colors">{item.label}</Link>
              )
            ))}
          </nav>
        )}

        {/* CTA slot + extras */}
        <div className="flex items-center gap-3">
          {extra}
          {resolvedCta.map((action, i) => {
            const key = action.href ?? action.label;
            if (action.variant === 'icon') {
              return (
                <button key={key} type="button" onClick={action.onClick} className="relative p-1.5 rounded-lg hover:bg-surface-100 dark:hover:bg-surface-800 text-surface-500 transition-colors" aria-label={action.label}>
                  {action.icon}
                </button>
              );
            }
            if (action.variant === 'secondary' || (resolvedCta.length > 1 && i < resolvedCta.length - 1)) {
              return (
                <Link key={key} to={action.href ?? '#'} onClick={action.onClick as any} className="btn-secondary text-sm !py-2 !px-5">{action.label}</Link>
              );
            }
            return (
              <Link key={key} to={action.href ?? '#'} onClick={action.onClick as any} className="btn-primary text-sm !py-2 !px-5">{action.label}</Link>
            );
          })}
        </div>
      </div>
    </header>
  );
}
