// Auto-generated by scripts/build-partials.js — DO NOT EDIT DIRECTLY
// Run `node scripts/build-partials.js` to regenerate.
// HAND-EDITED in the UX audit fix (F-C-09, F-C-20, F-C-23, F-C-25) and the SEO fix (F-F-12: every internal href in the trailing-slash form): scripts/build-partials.js must get the same change, or be retired, before anyone re-runs it.
//
// CTA Slot Contract:
//   cta prop accepts CtaAction[] with { label, href, variant?, icon? }
//   Empty array hides CTAs. Omitted prop uses variant default.

import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import BrandMark from './BrandMark';
import SkipLink from './SkipLink';
import ThemeToggle from './ThemeToggle';

// ─── Types ────────────────────────────────────────────────────

export type CtaVariant = 'primary' | 'secondary' | 'icon';

export interface CtaAction {
  label: string;
  href?: string;
  onClick?: () => void;
  variant?: CtaVariant;
  icon?: ReactNode;
}

export type HeaderVariant = 'landing' | 'marketing' | 'legal' | 'app';

export interface HeaderProps {
  /** Determines default nav items and default CTA */
  variant: HeaderVariant;
  /** Override default CTAs. Pass [] to hide. */
  cta?: CtaAction[];
  /** Override default nav items */
  navItems?: Array<{ label: string; href: string }>;
  /** Suppress the entire CTA area (shortcut for cta=[]) */
  hideCta?: boolean;
  /** Replaces the built-in theme toggle that sits after the nav. Pass null to show none. */
  extra?: ReactNode;
  className?: string;
}

// ─── Icon components (inline SVGs) ──────────────────────────

function BellIcon({ className }: { className?: string }) {
  return (
    <svg className={className ?? 'w-5 h-5'} viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="M10 2a6 6 0 00-6 6v3l-1 3h14l-1-3V8a6 6 0 00-6-6z"/>
      <path d="M7.5 14a2.5 2.5 0 005 0"/>
    </svg>
  );
}

function MenuIcon() {
  return <svg className="w-5 h-5" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"><path d="M3 5.5h14M3 10h14M3 14.5h14" /></svg>;
}

// ─── Variant defaults ───────────────────────────────────────

// The legal and contact pages used to get an empty nav and no CTAs, so a
// prospect arriving from a policy link or "Talk to sales" saw only a logo and had
// no route to Pricing or the trial. They share the marketing set, declared once
// so the two cannot drift apart again.
const MARKETING_NAV: Array<{ label: string; href: string }> = [
  { label: 'Features', href: '/#features' },
  { label: 'Pricing', href: '/pricing/' },
  { label: 'Methodology', href: '/methodology/' },
  { label: 'Sample Report', href: '/sample-report/' },
  { label: 'Security', href: '/security/' },
];

// Id of the mobile panel that the menu button's aria-controls points at. The
// panel element stays in the tree while closed (hidden and empty), so the
// reference always resolves: it used to be missing altogether (F-C-25).
const MOBILE_MENU_ID = 'site-mobile-navigation';

// Secondary first, primary last: the conversion action is the rightmost button.
const MARKETING_CTA: CtaAction[] = [
  { label: 'Book a Demo', href: '/demo/', variant: 'secondary' },
  { label: 'Start Free Trial', href: '/signup/', variant: 'primary' },
];

const DEFAULT_NAV: Record<HeaderVariant, Array<{ label: string; href: string }>> = {
  landing: [
    { label: 'Features', href: '#features' },
    { label: 'How It Works', href: '#how-it-works' },
    { label: 'Pricing', href: '/pricing/' },
    { label: 'Methodology', href: '/methodology/' },
    { label: 'Security', href: '/security/' },
  ],
  marketing: MARKETING_NAV,
  legal: MARKETING_NAV,
  app: [
  ],
};

const DEFAULT_CTA: Record<HeaderVariant, CtaAction[]> = {
  landing: [
    { label: 'Log In', href: '/login/', variant: 'secondary' },
    { label: 'Start Free Trial', href: '/signup/', variant: 'primary' },
  ],
  marketing: MARKETING_CTA,
  legal: MARKETING_CTA,
  app: [
    { label: 'Notifications', icon: <BellIcon />, variant: 'icon' },
  ],
};

const STICKY: Record<HeaderVariant, boolean> = {
  landing: true,
  marketing: true,
  legal: false,
  app: false,
};

// ─── Component ───────────────────────────────────────────────

export default function Header({ variant, cta, navItems, hideCta, extra, className }: HeaderProps) {
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const resolvedNav = navItems ?? DEFAULT_NAV[variant];
  const resolvedCta = hideCta ? [] : (cta ?? DEFAULT_CTA[variant]);
  const isSticky = STICKY[variant];
  const showMobileMenuButton = resolvedNav.length > 0 || resolvedCta.some((action) => action.href);
  const menuButtonRef = useRef<HTMLButtonElement>(null);

  // Escape closes the mobile panel and puts focus back on the toggle.
  // Deliberately NOT a focus trap: this panel expands inline in document
  // flow rather than overlaying the page, so the content below stays
  // visible and reachable — trapping Tab inside it would strand the user.
  useEffect(() => {
    if (!mobileNavOpen) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== 'Escape') return;
      setMobileNavOpen(false);
      menuButtonRef.current?.focus();
    };
    document.addEventListener('keydown', onKeyDown);
    return () => document.removeEventListener('keydown', onKeyDown);
  }, [mobileNavOpen]);

  return (
    <header
      className={`${isSticky ? 'sticky top-0 ' : ''}z-50 border-b border-surface-200/80 dark:border-surface-800/80 bg-white/90 dark:bg-surface-900/90 backdrop-blur-md${className ? ' ' + className : ''}`}>
      <SkipLink />
      <div className="max-w-7xl mx-auto px-6 py-3 flex items-center justify-between">
        {/* Logo */}
        <Link to="/" className="flex items-center gap-2.5">
          <BrandMark />
          <span className="font-semibold text-sm text-surface-900 dark:text-white tracking-tight">Eco-Auditor</span>
        </Link>

        {/* Nav items */}
        {resolvedNav.length > 0 && (
          <nav className="hidden md:flex items-center gap-6 text-sm" aria-label="Main navigation">
            {resolvedNav.map((item) => (
              item.href.startsWith('#') ? (
                <a key={item.href} href={item.href} className="inline-flex items-center no-underline text-surface-600 dark:text-surface-400 hover:text-surface-900 dark:hover:text-white transition-colors">{item.label}</a>
              ) : (
                <Link key={item.href} to={item.href} className="inline-flex items-center no-underline text-surface-600 dark:text-surface-400 hover:text-surface-900 dark:hover:text-white transition-colors">{item.label}</Link>
              )
            ))}
          </nav>
        )}

        {/* CTA slot + extras */}
        <div className="flex items-center gap-3">
          {showMobileMenuButton && (
            <button
              type="button"
              ref={menuButtonRef}
              onClick={() => setMobileNavOpen((open) => !open)}
              className="md:hidden p-1.5 rounded-lg hover:bg-surface-100 dark:hover:bg-surface-800 text-surface-500 transition-colors"
              aria-label="Toggle navigation menu"
              aria-expanded={mobileNavOpen}
              aria-controls={MOBILE_MENU_ID}
            >
              <MenuIcon />
            </button>
          )}
          {extra === undefined ? <ThemeToggle /> : extra}
          {resolvedCta.map((action) => {
            const key = action.href ?? action.label;
            if (action.variant === 'icon') {
              return (
                <button key={key} type="button" onClick={action.onClick} className="relative p-1.5 rounded-lg hover:bg-surface-100 dark:hover:bg-surface-800 text-surface-500 transition-colors" aria-label={action.label}>
                  {action.icon}
                </button>
              );
            }
            // Styled by declared intent only. Restyling every CTA but the last as
            // secondary turned the declared-primary "Start Free Trial" into an
            // outlined button on every marketing page.
            return (
              <Link key={key} to={action.href ?? '#'} onClick={action.onClick} className={`hidden sm:inline-flex ${action.variant === 'secondary' ? 'btn-secondary' : 'btn-primary'} text-sm !py-2 !px-5`}>{action.label}</Link>
            );
          })}
        </div>
      </div>
      {showMobileMenuButton && (
        <div id={MOBILE_MENU_ID} hidden={!mobileNavOpen} className="md:hidden border-t border-surface-200/80 dark:border-surface-800/80 bg-white dark:bg-surface-900">
          {mobileNavOpen && resolvedNav.length > 0 && (
            <nav className="px-6 py-4 space-y-1" aria-label="Mobile navigation">
              {resolvedNav.map((item) => (
                item.href.startsWith('#') ? (
                  <a key={item.href} href={item.href} onClick={() => setMobileNavOpen(false)} className="block rounded-lg px-3 py-2 text-sm font-medium no-underline text-surface-700 dark:text-surface-300 hover:bg-surface-100 dark:hover:bg-surface-800 transition-colors">{item.label}</a>
                ) : (
                  <Link key={item.href} to={item.href} onClick={() => setMobileNavOpen(false)} className="block rounded-lg px-3 py-2 text-sm font-medium no-underline text-surface-700 dark:text-surface-300 hover:bg-surface-100 dark:hover:bg-surface-800 transition-colors">{item.label}</Link>
                )
              ))}
            </nav>
          )}
          {mobileNavOpen && resolvedCta.some((action) => action.href) && (
            <div className="px-6 pb-4 flex flex-col gap-2">
              {resolvedCta.filter((action) => action.href).map((action) => (
                <Link
                  key={action.href ?? action.label}
                  to={action.href ?? '#'} 
                  onClick={() => { action.onClick?.(); setMobileNavOpen(false); }}
                  className={action.variant === 'secondary' ? 'btn-secondary justify-center text-sm !py-2 !px-5' : 'btn-primary justify-center text-sm !py-2 !px-5'}
                >
                  {action.label}
                </Link>
              ))}
            </div>
          )}
        </div>
      )}
    </header>
  );
}
